version: "3.9"

services:
  elixir_pokedex:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    image: elixir_pokedex:latest
    container_name: elixir_pokedex
    working_dir: /app
#    command: tail -f /dev/null
    command: mix serve
    security_opt:
      - seccomp:unconfined
    env_file:
      - .env.dev
    ports:
      - 4000:4000
      - 4369:4369
    volumes:
      - .:/app
      - ./.volumes/elixir_pokedex/_build:/app/_build
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push

  grafana:
    image: grafana/grafana:8.1.2
    ports:
      - 5000:3000
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    depends_on:
      - tempo

  loki:
    image: grafana/loki:2.3.0
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml

  tempo:
    image: grafana/tempo:1.1.0
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - 8000:8000 # tempo
      - 55681:55681 # otlp http
