global:
  scrape_interval:     5s
  evaluation_interval: 5s

  external_labels:
      monitor: 'pokedex'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pokedex'
    static_configs:
      - targets: ['elixir_pokedex:4000']
